### ISSUE TITLE
Flashing BBB from Element14

### ISSUE THREAD

**Issue by uklawitter** [jadonk/buildroot#5]
Hi,

I have a Flashing SD card that works for a beagleboard from BeagleBoard.org. If I try to flash the BBB from Element14, the beagle starts without using SD card.

Any suggestions?

THX
uklawitter

**Comment by jadonk** [comment]
Behavior of the 2 boards should be identical. I don't understand why you are surprised when the Beagle starts from the SD card. I'm closing this as it seems it should be on http://beagleboard.org/discuss, not related to Buildroot.
